name: 'Test Scanner'
description: 'This action scans the repository for manifest & lock files and generates a series of reports for visibility'
author: ''
inputs:
  repository_name:
    description: 'Repository name with owner, used for reporting only. For example, ministryofjustice/opg-repository-scanner'
    default: ${{ github.repository }}
  source_directory:
    required: false
    description: 'Directory to use as the base for scanning.'
    default: ${{ github.workspace }}
  source_exclude:
    required: false
    description: 'List of folders / filepaths to exclude from all filesystem operations. This is parsed using JSON.parse to convert from a string.'
    default: '["(__samples__/*)", "(__tests__/*)", "(node_modules/*)","(vendor/*)"]'
outputs:
  artifact_storage_directory:
    description: "Artifact storage directory"
    value: ${{ steps.scanner_runner.outputs.artifact_directory }}

runs:
  using: "composite"
  steps:
    - id: checkout
      name: Checkout code
      uses: actions/checkout@v2
    - id: setup-python-3
      name: Setup python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.7'
    - id: pip-install
      name: Run pip install
      shell: bash
      run: |
        pip --disable-pip-version-check install -r ${{ github.action_path }}/./app/requirements.txt
    - id: scanner_runner
      name: Run python script
      shell: bash
      run: |
        python ${{ github.action_path }}/./app/main.py \
          --repository='${{ inputs.repository_name }}' \
          --directory='${{ inputs.source_directory }}' \
          --exclude='${{ inputs.source_exclude }}'
    - id: upload
      name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: 'repository-scan-result'
        path: ${{ steps.scanner_runner.outputs.artifact_directory }}
