name: '[Python] Scan self using main'
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  python_scan_self:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: local test
        uses: ./
