name: 'Scanner'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  scan_self:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: local test
        uses: ./
